/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.cmu.partytracer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int info_waiting=0x7f020001;
        public static final int marker=0x7f020002;
        public static final int marker_destination=0x7f020003;
        public static final int marker_me=0x7f020004;
        public static final int marker_unknown=0x7f020005;
        public static final int menu_settings=0x7f020006;
        public static final int menu_stop=0x7f020007;
        public static final int menu_viewall=0x7f020008;
        public static final int menu_zoom=0x7f020009;
    }
    public static final class id {
        public static final int active=0x7f050010;
        public static final int addcategory=0x7f050006;
        public static final int addinvitedusers=0x7f050004;
        public static final int allactiveinvites=0x7f05001e;
        public static final int allalerts=0x7f050012;
        public static final int allinvitableusers=0x7f050015;
        public static final int allinvites=0x7f050023;
        public static final int alloptions=0x7f050008;
        public static final int allvotingoptions=0x7f050025;
        public static final int cancel=0x7f05000c;
        public static final int chooseinviteslabel=0x7f050014;
        public static final int create=0x7f05000d;
        public static final int createevent=0x7f05000b;
        public static final int donesetting=0x7f05001f;
        public static final int doneviewing=0x7f050024;
        public static final int donevoting=0x7f050026;
        public static final int eventdescription=0x7f050003;
        public static final int eventname=0x7f050001;
        public static final int exit=0x7f050013;
        public static final int finishedinviting=0x7f050016;
        public static final int inviteid=0x7f05001c;
        public static final int label1=0x7f050000;
        public static final int label2=0x7f050002;
        public static final int mainlayout=0x7f050020;
        public static final int mapview=0x7f050021;
        public static final int message_ok=0x7f05001b;
        public static final int message_text=0x7f05001a;
        public static final int module_invite=0x7f050017;
        public static final int module_trace=0x7f050018;
        public static final int request=0x7f05000e;
        public static final int scrollleft=0x7f050005;
        public static final int scrollright=0x7f050007;
        public static final int sendrequest=0x7f05001d;
        public static final int setcurrentinvite=0x7f05000f;
        public static final int test_tracetoggle=0x7f050019;
        public static final int timeoutentry=0x7f05000a;
        public static final int timeoutlabel=0x7f050009;
        public static final int vote=0x7f050011;
        public static final int zoomview=0x7f050022;
    }
    public static final class layout {
        public static final int creation=0x7f030000;
        public static final int invite=0x7f030001;
        public static final int inviteusers=0x7f030002;
        public static final int main=0x7f030003;
        public static final int message=0x7f030004;
        public static final int request=0x7f030005;
        public static final int setcurrent=0x7f030006;
        public static final int trace=0x7f030007;
        public static final int viewinvites=0x7f030008;
        public static final int voting=0x7f030009;
    }
    public static final class string {
        public static final int app_message=0x7f040002;
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int module_chooseinvites=0x7f040007;
        public static final int module_create=0x7f040005;
        public static final int module_invite=0x7f040004;
        public static final int module_request=0x7f040009;
        public static final int module_set=0x7f04000a;
        public static final int module_trace=0x7f040003;
        public static final int module_view=0x7f040006;
        public static final int module_vote=0x7f040008;
    }
}
