/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package project.invite;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int active=0x7f05000b;
        public static final int addoption=0x7f050006;
        public static final int alloptions=0x7f050007;
        public static final int cancel=0x7f050009;
        public static final int create=0x7f05000a;
        public static final int createevent=0x7f050008;
        public static final int eventdescription=0x7f050003;
        public static final int eventname=0x7f050001;
        public static final int invitable=0x7f050005;
        public static final int invitelabel=0x7f050004;
        public static final int label1=0x7f050000;
        public static final int label2=0x7f050002;
        public static final int vote=0x7f05000c;
    }
    public static final class layout {
        public static final int creation=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_create=0x7f040003;
        public static final int app_name=0x7f040001;
        public static final int app_view=0x7f040004;
        public static final int hello=0x7f040000;
        public static final int invite_prompt=0x7f040002;
    }
}
